### ISSUE TITLE
Export calendar to multiple .ics files per SIG

### ISSUE THREAD

**Issue by reteps** [acm-uiuc/website#152]
When an event is added via the UI, it should generate an ICS file for each SIG. This allows members to follow each SIGs calendar in Google Calendar, etc.

**Comment by reteps** [comment]
SIGPwny does something similar.

**Comment by devksingh4** [comment]
Implemented in https://github.com/acm-uiuc/core-api/pull/3

Proxied as `https://ical.acm.illinois.edu/HOST` where HOST is case-sensitive.
